---
  env:
    browser: true
    node: true
  extends: standard
  rules:
    semi:
      - 2
      - always
    space-before-function-paren:
      - 2
      -
        anonymous: always
        named: never
